# `numpy`

> Joseph P. Vantassel

This notebook presents a brief overview of `numpy` for numerical operations in Python.

## What is `numpy`

- `numpy` is an open-source Python package for numerical operations in Python.
- It is built primarily using c-compiled extensions, meaning it is fast and memory efficient.
- `numpy` is not part of the standard library and therefore needs to installed.
- We can install it using `pip` as follows, do not forget to restart your kernel after the installation.

In [2]:
!pip install numpy

In [3]:
import numpy as np

## `ndarray`

- The fundemental building block of `numpy` is the n-dimensional array `ndarray`.
- We can create an `ndarray` from any Python `iterable` (e.g., `list`, `tuple`, etc.).
- Arrays are by default row-major (i.e., c-style). Although you can also do column major.

### 1D array

In [8]:
my_1d_array = np.array([0, 1, 1, 2, 3])
print(my_1d_array)
print(type(my_1d_array))

[0 1 1 2 3]
<class 'numpy.ndarray'>


In [13]:
print("length", len(my_1d_array))
print("shape", my_1d_array.shape)
print("size", my_1d_array.size)
print("dtype", my_1d_array.dtype)

length 5
shape (5,)
size 5
dtype int64


### 2D array - Matrix

In [22]:
my_2d_array = np.array([[1,1,1],[2,2,2],[3,3,3,]], dtype=None)
print(my_2d_array)
print(type(my_2d_array))

[[1 1 1]
 [2 2 2]
 [3 3 3]]
<class 'numpy.ndarray'>


In [23]:
print("length", len(my_2d_array))
print("shape", my_2d_array.shape)
print("size", my_2d_array.size)
print("dtype", my_2d_array.dtype)

length 3
shape (3, 3)
size 9
dtype int64


## Tools

There is an incredible amount of operations you can perform with `numpy`.

We could easily spend several days covering it in detail.

To list a few of its most helpful features:

- linear algebra (`np.linalg`)
- Fourier transform (`np.fft`)
- Random number generation (`np.random`)
- Library of handy matrices (`np.matlib`)
- Input/Output (`.npy` and `.npy` file formats)

But after this course you go to [numpy.org](https://numpy.org/doc/stable/reference/routines.html) and look at everything `numpy` has to offer.